//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TurfModelContainer1 : DbContext
    {
        public TurfModelContainer1()
            : base("name=TurfModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TurfUser> TurfUsers { get; set; }
        public virtual DbSet<TurfMaster> TurfMasters { get; set; }
        public virtual DbSet<TurfGroup> TurfGroups { get; set; }
        public virtual DbSet<TypeofTurf> TypeofTurfs { get; set; }
        public virtual DbSet<TurfMedia> TurfMedias { get; set; }
        public virtual DbSet<TurfBooking> TurfBookings { get; set; }
        public virtual DbSet<TurfFecilityMaster> TurfFecilityMasters { get; set; }
        public virtual DbSet<TurfFacilityList> TurfFacilityLists { get; set; }
        public virtual DbSet<TurfBookingFacilityList> TurfBookingFacilityLists { get; set; }
    }
}
