//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurfBookingFacilityList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TurfBookingFacilityList()
        {
            this.Amount = 0.00m;
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int TurfBookingId { get; set; }
        public int TurfFacilityListId { get; set; }
    
        public virtual TurfBooking TurfBooking { get; set; }
        public virtual TurfFacilityList TurfFacilityList { get; set; }
    }
}
