//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace websvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurfGroup
    {
        public int Id { get; set; }
        public string Discription { get; set; }
        public int TurfUserId { get; set; }
    
        public virtual TurfUser TurfUser { get; set; }
    }
}
