//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurfManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurfMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TurfMaster()
        {
            this.TurfBookings = new HashSet<TurfBooking>();
            this.TurfFacilityLists = new HashSet<TurfFacilityList>();
            this.TurfMedias = new HashSet<TurfMedia>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public int TurfGroupId { get; set; }
        public int TurfUserId { get; set; }
        public int TypeofTurfId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurfBooking> TurfBookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurfFacilityList> TurfFacilityLists { get; set; }
        public virtual TurfUser TurfUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurfMedia> TurfMedias { get; set; }
        public virtual TypeofTurf TypeofTurf { get; set; }
    }
}
